version: '3.8'
services:

  mongo:
    image: mongo:6.0
    container_name: backpaws-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}

  backpaws:
    build:
      context: .
      dockerfile: dockerfile
    container_name: backpaws-spring
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8081:8080"
    volumes:
      - ${PHOTO_STORAGE_PATH}:/app/photos # Mount host's photo directory to container
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=${MONGO_DB}
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_ROOT_USER}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_ROOT_PASS}
      - PHOTO_PATH=/app/photos

volumes:
  mongo-data:
